#!/usr/bin/env bash
# Add multiple tags to an image with Docker Hub automated builds
# Credit to Nigel Brown
# https://windsock.io/automated-docker-image-builds-with-multiple-tags/

set -e

echo "Checking for additional tags related to $SOURCE_BRANCH"

push_tags () {
    echo "Tagging ${tag} from ${IMAGE_NAME}"
    docker tag ${DOCKER_REPO}:${base_tag} ${DOCKER_REPO}:${tag}
    docker push ${DOCKER_REPO}:${tag}
}

# Tag and push image for each additional tag
case $SOURCE_BRANCH in
    "stretch")
        base_tag="stretch"
        tags=( "latest" )
        for tag in "${tags[@]}"; do
            push_tags
        done
        base_tag="stretch-dev"
        tags=( "dev" )
        for tag in "${tags[@]}"; do
            push_tags
        done
        ;;
    *)
        :
        ;;
esac
