#!/usr/bin/env bash
# Build additional targets

set -e

TARGETS='dev'
BUILD_TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

# Build each target
build_target () {
    docker build \
        --label org.opencontainers.image.created="${BUILD_TIMESTAMP}" \
        --label org.opencontainers.image.authors="docker-jupyterlab@rexypoo.com" \
        --label org.opencontainers.image.url="https://hub.docker.com/r/rexypoo/jupyterlab" \
        --label org.opencontainers.image.documentation="https://hub.docker.com/r/rexypoo/jupyterlab" \
        --label org.opencontainers.image.source="https://github.com/Rexypoo/docker-jupyterlab" \
        --label org.opencontainers.image.version="0.1a" \
        --label org.opencontainers.image.revision="${SOURCE_COMMIT}" \
        --label org.opencontainers.image.vendor="rexypoo" \
        --label org.opencontainers.image.licenses="MIT" \
        --label org.opencontainers.image.ref.name="${IMAGE_NAME}-${TARGET}" \
        --label org.opencontainers.image.title="rexypoo/jupyterlab:${IMAGE_NAME}-${TARGET}" \
        --label org.opencontainers.image.description="Self-contained Jupyterlab image on Debian Stretch." \
        --label org.label-schema.docker.cmd="docker run -d \
    -p 127.0.0.1:8888:8888 \
    -v ~/notebooks:/jupyter/notebooks \
    -v /srv/jupyter/config:/jupyter/config \
    -v /srv/jupyter/kernels:/jupyter/kernels \
    -v /srv/jupyter/ve:/jupyter/ve \
    --name jupyterlab \
    --restart always \
    rexypoo/jupyterlab" \
        --label org.label-schema.docker.cmd.devel="docker run -it --rm rexypoo/jupyterlab:dev" \
        --label org.label-schema.docker.cmd.debug="docker exec -it --user root <container> bash" \
        --label org.label-schema.docker.cmd.help="docker run -it --rm rexypoo/jupyterlab jupyter lab --help" \
        --target $TARGET \
        -t ${IMAGE_NAME}-${TARGET} .
    docker push ${IMAGE_NAME}-${TARGET}
}

for TARGET in $TARGETS; do
    echo "Creating target: $TARGET"
    build_target
done
